services:
  - type: web
    name: festie-results-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: FIREBASE_API_KEY
        sync: false
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: COOKIE_SAMESITE
        value: None
      - key: COOKIE_SECURE
        value: true